version: '3.8'

services:
  voice_frontend:
    build: 
      context: ./frontend-react
      args:
        - VITE_API_URL=https://voice-backend.marketbytes.in
        - VITE_WS_URL=wss://voice-backend.marketbytes.in
    container_name: voice_frontend
    restart: always
    ports:
      - "3010:80"
    
  voice_backend:
    build: ./backend
    container_name: voice_backend
    restart: always
    environment:
      - DATABASE_URL=mysql+pymysql://root:marketbytesshared%409633@shared-mysql:3306/voicedb
    ports:
      - "8010:8010"
    networks:
      - default
      - shared-db-network

networks:
  default:
  shared-db-network:
    external: true
